- id: '2579374675082'
  alias: Startup - Theme
  trigger:
  - event: start
    platform: homeassistant
  action:
  - data:
      name: slate
    service: frontend.set_theme
  initial_state: 'on'
  mode: single
- id: '1495373253029'
  alias: Notification - Garage Door Closed
  description: Close notification for Garage Door
  trigger:
  - entity_id: cover.garage_door
    from: open
    platform: state
    to: closed
    for: 00:00:10
  action:
  - data:
      entity_id: light.notify
      rgb_color:
      - 246
      - 255
      - 254
    entity_id: light.notify
    service: light.turn_on
  - entity_id: light.notify
    service: light.turn_off
  - data:
      message: The Garage door closed
    service: notify.mobile_app_mobile
  - data:
      message: The Garage door closed
    service: notify.mobile_app_tablet
  mode: single
- id: '1502817251957'
  alias: Sunrise
  description: Morning lighting and switch automation for office, coffee, back deck
    water fountain and bed lights.
  trigger:
  - entity_id: sun.sun
    for: 02:00
    from: below_horizon
    platform: state
    to: above_horizon
  condition:
  - condition: state
    entity_id: switch.pergola_lights
    state: 'on'
  action:
  - entity_id: switch.bedroom_bed_light_switch
    service: switch.turn_off
  - entity_id: switch.kitchen_coffee_light_switch
    service: switch.turn_off
  - entity_id: switch.office_office_lamp_switch
    service: switch.turn_off
  - entity_id: light.office_light
    service: light.turn_off
  - entity_id: switch.backyard_water_fountain_switch
    service: switch.turn_off
  - service: switch.turn_off
    data: {}
    entity_id: switch.frontyard_frontyard_lights_switch
  - service: switch.turn_off
    data: {}
    entity_id: switch.backyard_backyard_lights_switch
  mode: single
- id: '1502832340378'
  alias: Lighting - Office bedtime
  description: Lighting automation for the office for the night
  trigger:
  - at: '19:30'
    platform: time
  condition: []
  action:
  - data: {}
    entity_id: switch.office_lamp
    service: switch.turn_off
  - entity_id: light.office_light
    service: light.turn_off
  - service: light.turn_off
    data: {}
    entity_id: light.desk
  - service: light.turn_off
    data: {}
    entity_id: light.under_desk
  mode: single
- id: '1558218116963'
  alias: Sunset
  description: Evening lighting and switch automation for office, coffee, back deck
    water fountain and bed lights.
  trigger:
  - entity_id: sun.sun
    for: 00:30
    from: above_horizon
    platform: state
    to: below_horizon
  condition: []
  action:
  - data: {}
    entity_id: switch.backyard_pergola_lights_switch
    service: switch.turn_on
  - entity_id: switch.bedroom_bed_light_switch
    service: switch.turn_off
  - entity_id: switch.kitchen_coffee_light_switch
    service: switch.turn_on
  - entity_id: switch.backyard_water_fountain_switch
    service: switch.turn_off
  - service: switch.turn_on
    data: {}
    entity_id: switch.frontyard_frontyard_lights_switch
  - service: switch.turn_on
    data: {}
    entity_id: switch.backyard_backyard_lights_switch
  mode: single
- id: '1558230115098'
  alias: Notification - Home Assistant Startup
  trigger:
  - event: start
    platform: homeassistant
  condition: []
  action:
  - data:
      message: Home Assistant started
    service: notify.mobile_app_mobile
  - data:
      message: Home Assistant started
    service: notify.mobile_app_tablet
  mode: single
- id: '1558230236693'
  alias: Notification - Home Assistant Shutdown
  trigger:
  - event: shutdown
    platform: homeassistant
  condition: []
  action:
  - data:
      message: Home Assistant has shutdown
    service: notify.mobile_app_mobile
  - data:
      message: Home Assistant has shutdown
    service: notify.ios_tablet
  mode: single
- id: '1558890166958'
  alias: Auto Lock - Front Door
  trigger:
  - entity_id: lock.front_door
    for: 00:30
    from: locked
    platform: state
    to: unlocked
  condition: []
  action:
  - data:
      entity_id: lock.front_door
    entity_id: lock.front_door
    service: lock.lock
- id: '1538860156959'
  alias: Auto Lock - Back Door
  trigger:
  - entity_id: lock.back_door
    for: 00:30
    from: locked
    platform: state
    to: unlocked
  condition: []
  action:
  - data:
      entity_id: lock.back_door
    entity_id: lock.back_door
    service: lock.lock
- id: '1559450583488'
  alias: Auto Lock - Garage Door
  trigger:
  - entity_id: lock.garage_door
    for: 00:30
    from: unlocked
    platform: state
    to: locked
  condition:
  - condition: sun
    before: sunrise
    after: sunset
  action:
  - entity_id: lock.garage_door
    service: lock.lock
  mode: single
- id: '1569672724355'
  alias: Startup - HomeKit
  trigger:
  - event_data: {}
    event_type: zwave.network_ready
    platform: event
  - event_data: {}
    event_type: zwave.network_complete
    platform: event
  - event_data: {}
    event_type: zwave.network_complete_some_dead
    platform: event
  condition: []
  action:
  - service: homekit.start
- id: '1579996885432'
  alias: Notification - Garage Door Open
  description: ''
  trigger:
  - entity_id: cover.garage_door
    from: closed
    platform: state
    to: open
  condition: []
  action:
  - data:
      message: The Garage door opened
    service: notify.mobile_app_mobile
  - data:
      message: The Garage door opened
    service: notify.mobile_app_tablet
  - data:
      entity_id: light.notify
      rgb_color:
      - 25
      - 255
      - 25
    entity_id: light.notify
    service: light.turn_on
  mode: single
- id: '1580003362412'
  alias: Notification - Home Assistant Update
  description: ''
  trigger:
  - entity_id: sensor.home_assistant_update
    from: Current Release
    platform: state
    to: Update Available
  condition: []
  action:
  - data:
      message: Home Assistant {{ states.sensor.latest_version.state }} is available.
    service: notify.mobile_app_mobile
  - data:
      message: Home Assistant {{ states.sensor.latest_version.state }} is available.
    service: notify.mobile_app_tablet
  mode: single
- id: '1580077708650'
  alias: Notification - Home Assistant Community Store Update
  description: Home Assistant Community Store Update Notification
  trigger:
  - above: '0'
    entity_id: sensor.hacs
    platform: numeric_state
  condition: []
  action:
  - data:
      message: Home Assistant Community Store has {{ states('sensor.hacs') }} pending
        update(s) available.
    service: notify.mobile_app_mobile
  - data:
      message: Home Assistant Community Store has {{ states('sensor.hacs') }} pending
        update(s) available.
    service: notify.mobile_app_tablet
  mode: single
- id: '1580224449809'
  alias: Lighting - Work
  description: Morning work automation for lights in the office
  trigger:
  - at: 05:00
    platform: time
  condition:
  - condition: state
    entity_id: binary_sensor.workday_sensor
    state: 'on'
  - condition: state
    entity_id: sun.sun
    state: below_horizon
  action:
  - data:
      brightness: 50
    entity_id: light.office_light
    service: light.turn_on
  - entity_id: light.desk
    service: light.turn_on
  - entity_id: switch.kitchen_coffee_light
    service: switch.turn_on
  - service: light.turn_on
    data: {}
    entity_id: light.under_desk
  mode: single
- id: '1580477302204'
  alias: Snapshot - Nightly
  description: Nightly Auto Snapshot
  trigger:
  - at: 02:00
    platform: time
  condition: []
  action:
    service: auto_backup.snapshot_full
    data_template:
      name: '{{ now().strftime(''%b-%d-%Y'') }}'
      keep_days: 7
- id: '1580477536052'
  alias: Notification - Snapshot Failure
  description: Notification on snapshot failure
  trigger:
  - event_data: {}
    event_type: auto_backup.snapshot_failed
    platform: event
  condition: []
  action:
    service: persistent_notification.create
    data_template:
      title: Snapshot Failed.
      message: 'Name: {{ trigger.event.data.name }}

        Error: {{ trigger.event.data.error }}'
- id: '1603110760010'
  alias: Goodnight - Lighting
  description: Lighting automation
  trigger:
  - platform: time
    at: '22:30'
  condition: []
  action:
  - service: switch.turn_off
    data: {}
    entity_id: switch.backyard_pergola_lights_switch
  - service: switch.turn_off
    data: {}
    entity_id: switch.backyard_backyard_lights_switch
  - service: switch.turn_off
    data: {}
    entity_id: switch.frontyard_frontyard_lights_switch
  mode: single
- id: '1603927830253'
  alias: Doorbell
  description: Doorbell Notification
  trigger:
  - platform: state
    entity_id: binary_sensor.doorbell_front_door
    from: 'off'
    to: 'on'
  condition:
  - condition: time
    after: '10:00'
  action:
  - service: notify.mobile_app_tablet
    data:
      message: Someone is at the frontdoor
      data:
        attachment:
          content-type: jpeg
        push:
          category: camera
        entity_id: camera.front_door
  - service: notify.mobile_app_mobile
    data:
      message: Someone is at the frontdoor
      data:
        attachment:
          content-type: jpeg
        push:
          category: camera
        entity_id: camera.front_door
  - service: camera.play_stream
    data:
      media_player: media_player.office_hub,media_player.kitchen_hub, media_player.bedroom_hub,
        media_player.guest_bedroom_hub, media_player.basement_hub,
    entity_id: camera.front_door
  - delay: 00:00:60
  - service: media_player.turn_off
    entity_id: media_player.office_hub,media_player.kitchen_hub, media_player.bedroom_hub,
      media_player.guest_bedroom_hub, media_player.basement_hub, media_player.bedroom_tv,
      media_player.guest_bedroom_tv, media_player.livingroom_tv
  mode: single
- id: '1603982875632'
  alias: Cleanup
  description: Cleanup Tasks
  trigger:
  - platform: time
    at: 00:30:00
  condition: []
  action:
  - service: tts.clear_cache
    data: {}
  mode: single
- id: '1603986314847'
  alias: Driveway
  description: Driveway Notifications
  trigger:
  - platform: numeric_state
    entity_id: image_processing.doods_driveway
    above: '0'
  condition: []
  action:
  - service: notify.mobile_app_mobile
    data:
      message: Someone is in the driveway
      data:
        attachment:
          content-type: jpeg
        push:
          category: camera
        entity_id: camera.driveway
  - service: notify.mobile_app_tablet
    data:
      message: Someone is in the driveway
      data:
        attachment:
          content-type: jpeg
        push:
          category: camera
        entity_id: camera.driveway
  mode: single
- id: '1606135576092'
  alias: Notification - Synology Update
  description: Synology Update Notification
  trigger:
  - platform: state
    entity_id: binary_sensor.nas_update_available
    from: 'off'
    to: 'on'
  condition: []
  action:
  - data:
      message: Synology has pending update(s) available.
    service: notify.mobile_app_mobile
  - data:
      message: Synology has pending update(s) available.
    service: notify.mobile_app_tablet
  mode: single
- id: '1606840874562'
  alias: 'Reminder: Dyson Filter Reminder'
  description: Dyson Filter Reminder
  trigger:
  - platform: numeric_state
    entity_id: sensor.filter_days_remaining
    below: '30'
  condition: []
  action:
  - service: notify.mobile_app_mobile
    data:
      message: Please order a new filter for the Dyson Fan, the filter has {{ states('sensor.filter_days_remaining')
        }} days remaining.
  - service: notify.mobile_app_tablet
    data:
      message: Please order a new filter for the Dyson Fan, the filter has {{ states('sensor.filter_days_remaining')
        }} days remaining.
  mode: single
- id: '1606842109568'
  alias: 'Alert: Dyson Filter Reminder'
  description: Dyson Filter Alert
  trigger:
  - platform: numeric_state
    entity_id: sensor.filter_days_remaining
    below: '30'
  condition: []
  action:
  - service: notify.mobile_app_mobile
    data:
      message: Please change the Dyson Fan, the filter has {{ states('sensor.filter_days_remaining')
        }} days remaining.
  - service: notify.mobile_app_tablet
    data:
      message: Please change the Dyson Fan, the filter has {{ states('sensor.filter_days_remaining')
        }} days remaining.
  mode: single
- id: '1609278551106'
  alias: Doods Driveway
  description: ''
  trigger:
  - platform: state
    entity_id: binary_sensor.motion_driveway
    from: 'off'
    to: 'on'
  condition: []
  action:
  - service: image_processing.scan
    data:
      entity_id: image_processing.doods_driveway
  mode: single
- id: '1610381562996'
  alias: Doods Front Deck
  description: ''
  trigger:
  - platform: state
    entity_id: binary_sensor.motion_front_deck
    from: 'off'
    to: 'on'
  condition: []
  action:
  - service: image_processing.scan
    data:
      entity_id: image_processing.doods_front_deck
  mode: single
- id: '1610393405292'
  alias: Doods Back Deck
  description: ''
  trigger:
  - platform: state
    entity_id: binary_sensor.motion_back_deck
    from: 'off'
    to: 'on'
  condition: []
  action:
  - service: image_processing.scan
    data:
      entity_id: image_processing.doods_back_deck
  mode: single
