homeassistant:
  # Name of the location where Home Assistant is running
  # name: Home
  # Location required to calculate the time the sun rises and sets
  # latitude: !secret latitude
  # longitude: !secret longitude
  # external_url: "https://home.giff.ca"
  # Impacts weather/sunrise data
  # elevation: !secret elevation
  # 'metric' for the metric system, 'imperial' for the imperial system
  # unit_system: metric
  # http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
  # time_zone: America/Edmonton
  # customize must nested within homeassistant entity
  customize: !include customize.yaml
  packages: !include_dir_named packages

# Enables the frontend
frontend:
  javascript_version: latest
  themes: !include_dir_merge_named themes

http:
  cors_allowed_origins:
  - !secret base_origin
  use_x_forwarded_for: true
  trusted_proxies:
  - !secret nginx_proxy
  - !secret hassio_proxy

# Core Components
config:
sun:
discovery:
conversation:
system_health:
mobile_app:
logbook:
recorder:
  purge_keep_days: 7
history:
logger:
  default: warning
updater:
  reporting: false
  include_used_components: true
tts:
  - platform: google_translate

# Simple Components

# Includes
automation: !include automations.yaml
binary_sensor: !include binary_sensor.yaml
group: !include group.yaml
camera: !include camera.yaml
ios: 
notify: !include notify.yaml
script: !include scripts.yaml
sensor: !include_dir_merge_list sensor
zone: !include zones.yaml

# Third Party Platforms
auto_backup:
  auto_purge: true

breaking_changes:

dyson:
  username: !secret dyson_username
  password: !secret dyson_password
  language: !secret dyson_language
  devices:
    - device_id: !secret dyson_bedroom_serial
      device_ip: !secret dyson_bedroom_ip

speedtestdotnet:
  scan_interval:
    minutes: 90
  monitored_conditions:
    - ping
    - download
    - upload

fastdotcom:

google:
  client_id: !secret google_client_id
  client_secret: !secret google_client_secret

google_assistant: !include google_assistant.yaml

media_player:
  - platform: androidtv
    name: Livingroom Android TV
    host: !secret living_room_tv_ip
  - platform: androidtv
    name: Bedroom Android TV
    host: !secret bedroom_tv_ip
  - platform: androidtv
    name: Guest Bedroom Android TV
    host: !secret guest_bedroom_tv_ip

stream:

image_processing: !include doods.yaml
