#  homeassistant:
#  customize: !include customize.yaml
#  packages: !include_dir_named packages

frontend:
  themes: !include_dir_merge_named themes

http:
  cors_allowed_origins:
  - !secret base_origin
  use_x_forwarded_for: true
  trusted_proxies:
  - !secret nginx_proxy
  - !secret hassio_proxy

# Core Components
default_config:
config:
sun:
discovery:
conversation:
system_health:
energy:
mobile_app:
logbook:
recorder:
  db_url: !secret mariadb_url
history:
logger:
  default: warning
tts:
  - platform: google_translate
my:
usb:


# Includes
automation: !include automations.yaml
binary_sensor: !include binary_sensor.yaml
camera: !include camera.yaml
google_assistant: !include google_assistant.yaml
homekit: !include homekit.yaml
ios:
notify: !include notify.yaml
script: !include scripts.yaml
sensor: !include_dir_merge_list sensor
zone: !include zones.yaml

influxdb:
  host: a0d7b954-influxdb
  port: 8086
  database: !secret influxdb_db
  username: !secret influxdb_username
  password: !secret influxdb_password
  max_retries: 3
  default_measurement: state

pyscript:
  allow_all_imports: true
  hass_is_global: true
  apps:
    mam:
      - service_name: get_mam_jsonLoad
        url: !secret mam_url
        cookie: !secret mam_cookie

spotify:
  client_id: !secret spotify_id

  client_secret: !secret spotify_secret

media_player:
  - platform: androidtv
    name: Livingroom Android TV
    host: !secret living_room_tv_ip
  - platform: androidtv
    name: Bedroom Android TV
    host: !secret bedroom_tv_ip
  - platform: androidtv
    name: Guest Bedroom Android TV
    host: !secret guest_bedroom_tv_ip

stream:
