###########################################
# Bedroom
########################################### 
- platform: group
  name: Bedroom Bed Lights
  entities:
    - light.bed_light_beth
    - light.bed_light_paul

- platform: group
  name: Desk Lights
  entities:
    - light.desk_key_light
    - light.under_desk

- platform: group
  name: Office Lamps
  entities:
    - light.office_lamp_left
    - light.office_lamp_right

- platform: group
  name: Office Lights
  entities:
    - light.desk_key_light
    - light.under_desk
    - light.office_lamps
    - light.office_flood_1
    - light.office_flood_2
    - light.office_flood_3
    - light.office_flood_4