- platform: slack
  name: slack_notify
  api_key: !secret slack_api
  default_channel: '#notifications'

- platform: group
  name: paul_devices
  services:
    - service: notify_mobile_app_mobile
    - service: notify_tablet_app_mobile

- platform: group
  name: family_devices
  services:
    - service: notify_mobile_app_mobile
    - service: notify_tablet_app_mobile

- platform: nfandroidtv
  name: Living Room TV
  host: !secret living_room_tv_ip

- platform: nfandroidtv
  name: Bedroom TV
  host: !secret bedroom_tv_ip

- platform: nfandroidtv
  name: Guest Bedroom TV
  host: !secret guest_bedroom_tv_ip