###########################################
# Work Calendar
###########################################

- platform: template
  sensors:
    work_meeting:
      friendly_name: 'Work Meeting'
      icon_template: 'mdi:calendar'
      entity_id: 'calendar.work'
      value_template: "{{ 'Busy' if is_state('calendar.work', 'on') else 'Free' }}"
