# Date & Time
- platform: time_date
  display_options:
    - 'time'
    - 'date'
    - 'time_date'
    - 'date_time'
    - 'time_utc'
    - 'beat'

- platform: template
  sensors:
    day:
      entity_id: sensor.date
      value_template: "{{ now().strftime('%A') }}"

    month:
      entity_id: sensor.date
      value_template: "{{ now().strftime('%B') }}"
    
    dateofthemonth:
      entity_id: sensor.date 
      value_template: >
        {% set suffix = ['st', 'nd', 'rd'] %}
        {% set day = now().day %}
        {% set index = 3 if day // 10 == 1 or day % 10 == 0 else (day % 10) - 1 %}
        {{ day~'th' if index > 2 else day~suffix[index] }}

- platform: template
  sensors:
    tomorrow:
      entity_id: sensor.tomorrow
      value_template: "{{(as_timestamp(now())+ (86400)) | timestamp_custom('%A',true)}}"

- platform: template
  sensors:
    nextday:
      entity_id: sensor.nextday
      value_template: "{{(as_timestamp(now())+ (172800)) | timestamp_custom('%A',true)}}"

- platform: template
  sensors:
    dayafter:
      entity_id: sensor.dayafter
      value_template: "{{(as_timestamp(now())+ (259200)) | timestamp_custom('%A',true)}}"      