

# Door Sensors

- platform: template
  sensors:
    front_door:
        value_template: >-
          {%- if is_state("binary_sensor.front_door", "on") %}
              Open
          {%- elif is_state("binary_sensor.front_door", "off") %}
              Closed
          {%- else %}
              Error
          {%- endif %}
        friendly_name: 'Front Door'
        icon_template: >-
            {%- if is_state('binary_sensor.front_door', 'off') %}
            mdi:door
            {%- elif is_state('binary_sensor.front_door', 'on') %}
            mdi:door-open
            {% else %}
            mdi:door
            {% endif %}   


- platform: template
  sensors:
    front_door_lock:
        value_template: >-
          {%- if is_state("lock.front_door", "locked") %}
              Locked
          {%- elif is_state("lock.front_door", "unlocked") %}
              Unlocked
          {%- else %}
              Error
          {%- endif %}

- platform: template
  sensors:
    back_door:
        value_template: >-
          {%- if is_state("binary_sensor.back_door", "on") %}
              Open
          {%- elif is_state("binary_sensor.back_door", "off") %}
              Closed
          {%- else %}
              Error
          {%- endif %}
        friendly_name: 'Back Door'
        icon_template: >-
            {%- if is_state('binary_sensor.back_door', 'off') %}
            mdi:door
            {%- elif is_state('binary_sensor.back_door', 'on') %}
            mdi:door-open
            {% else %}
            mdi:door
            {% endif %}   

- platform: template
  sensors:
    back_door_lock:
        value_template: >-
          {%- if is_state("lock.back_door", "locked") %}
              Locked
          {%- elif is_state("lock.back_door", "unlocked") %}
              Unlocked
          {%- else %}
              Error
          {%- endif %}


- platform: template
  sensors:
    garage_door:
        value_template: >-
          {%- if is_state("binary_sensor.garage_door", "on") %}
              Open
          {%- elif is_state("binary_sensor.garage_door", "off") %}
              Closed
          {%- else %}
              Error
          {%- endif %}
        friendly_name: 'Garage Door'
        icon_template: >-
            {%- if is_state('binary_sensor.garage_door', 'off') %}
            mdi:door
            {%- elif is_state('binary_sensor.garage_door', 'on') %}
            mdi:door-open
            {% else %}
            mdi:door
            {% endif %} 