

# Door Sensors


- platform: template
  sensors:
    front_door_lock:
        value_template: >-
          {%- if is_state("lock.front_door", "locked") %}
              Locked
          {%- elif is_state("lock.front_door", "unlocked") %}
              Unlocked
          {%- else %}
              Error
          {%- endif %}


- platform: template
  sensors:
    back_door_lock:
        value_template: >-
          {%- if is_state("lock.back_door", "locked") %}
              Locked
          {%- elif is_state("lock.back_door", "unlocked") %}
              Unlocked
          {%- else %}
              Error
          {%- endif %}


- platform: template
  sensors:
    garage_door_lock:
        value_template: >-
          {%- if is_state("lock.garage_door", "locked") %}
              Locked
          {%- elif is_state("lock.garage_door", "unlocked") %}
              Unlocked
          {%- else %}
              Error
          {%- endif %}