###########################################
# Dyson Sensors
###########################################

- platform: template
  sensors:
    filter_days_remaining:
      friendly_name: "Filter Remaining"
      unit_of_measurement: 'days'
      value_template: "{{ (states('sensor.bedroom_filter_life')| float / 24) | round(0) }}"
      icon_template: mdi:air-filter