###########################################
# DNS IP
###########################################
- platform: dnsip

###########################################
# Certificate Expiry
###########################################
- platform: cert_expiry
  host: home.giff.ca

- platform: template
  sensors:
    ping:
      friendly_name: 'Ping'
      unit_of_measurement: 'ms'
      icon_template: 'mdi:dots-horizontal'
      entity_id: 'binary_sensor.ping_binary_sensor'
      value_template: "{{ state_attr('binary_sensor.ping_binary_sensor', 'round_trip_time_avg') }}"