

- platform: tautulli
  api_key: !secret tautulli_api
  host: !secret nas_address
  port: 8888
  monitored_conditions:
    - stream_count
    - stream_count_direct_play
    - stream_count_direct_stream
    - stream_count_transcode
    - total_bandwidth
    - wan_bandwidth

