###########################################
# Synology DSM
###########################################

- platform: synologydsm
  host: !secret nas_address
  port: !secret nas_port
  username: !secret nas_username
  password: !secret nas_password
  monitored_conditions:
    - cpu_total_load
    - cpu_system_load
    - memory_real_usage
    - memory_cached
    - memory_size
    - memory_available_real
    - network_up
    - network_down
    - disk_name
    - disk_device
    - disk_smart_status
    - disk_status
    - disk_temp
    - disk_exceed_bad_sector_thr
    - disk_below_remain_life_thr
    - volume_status
    - volume_device_type
    - volume_size_total
    - volume_size_used
    - volume_percentage_used
    - volume_disk_temp_avg
    - volume_disk_temp_max
