###########################################
# Location Sensor for Vehicles
###########################################

- platform: template
  sensors:
    audi_status:
      value_template: "{{ 'Home' if is_state('device_tracker.2015_audi_rs_5', 'home') else 'Driving' }}"


- platform: template
  sensors:
    f150_status:
      value_template: "{{ 'Home' if is_state('device_tracker.2013_ford_f150', 'home') else 'Driving' }}"

###########################################
# GPS Information for Vehicles
###########################################

- platform: template
  sensors:
    audi_longitude:
      friendly_name: 'RS5 Longitude'
      icon_template: 'mdi:crosshairs-gps'
      entity_id: 'device_tracker.2015_audi_rs_5'
      value_template: "{{ states.device_tracker['2015_audi_rs_5'].attributes.longitude }}"

- platform: template
  sensors:
    audi_latitude:
      friendly_name: 'RS5 Latitude'
      icon_template: 'mdi:crosshairs-gps'
      entity_id: 'device_tracker.2015_audi_rs_5'
      value_template: "{{ states.device_tracker['2015_audi_rs_5'].attributes.latitude }}"

- platform: template
  sensors:
    f150_longitude:
      friendly_name: 'F150 Longitude'
      icon_template: 'mdi:crosshairs-gps'
      entity_id: 'device_tracker.2013_ford_f_150'
      value_template: "{{ states.device_tracker['2013_ford_f_150'].attributes.longitude }}"

- platform: template
  sensors:
    f150_latitude:
      friendly_name: 'F150 Latitude'
      icon_template: 'mdi:crosshairs-gps'
      entity_id: 'device_tracker.2013_ford_f_150'
      value_template: "{{ states.device_tracker['2013_ford_f_150'].attributes.latitude }}"

###########################################
# Fuel Level for Vehicles
###########################################

- platform: template
  sensors:
    audi_gas:
      friendly_name: 'RS5 Fuel'
      unit_of_measurement: '%'
      icon_template: 'mdi:gas-station'
      entity_id: 'device_tracker.2015_audi_rs_5'
      value_template: "{{ states.device_tracker['2015_audi_rs_5'].attributes.fuel_level | round(0) }}"

- platform: template
  sensors:
    f150_gas:
      friendly_name: 'F150 Fuel'
      unit_of_measurement: '%'
      icon_template: 'mdi:gas-station'
      entity_id: 'device_tracker.2013_ford_f_150'
      value_template: "{{ states.device_tracker['2013_ford_f_150'].attributes.fuel_level | round(0) }}"
