###########################################
# Weather Sensors
###########################################

- platform: darksky
  api_key: !secret darksky_api
  forecast:
  - 0
  - 1
  - 2
  - 3
  - 4
  - 5
  - 6
  - 7
  hourly_forecast:
  - 0
  - 1
  - 2
  - 3
  - 4
  - 5
  - 6
  - 7
  - 8
  monitored_conditions:
  - icon
  - summary
  - daily_summary
  - dew_point
  - precip_probability
  - apparent_temperature
  - pressure
  - wind_speed
  - precip_type
  - precip_intensity
  - precip_probability
  - precip_accumulation 
  - cloud_cover
  - wind_bearing
  - wind_speed
  - wind_gust
  - humidity
  - sunrise_time
  - sunset_time
  - nearest_storm_distance
  - nearest_storm_bearing
  - moon_phase

- platform: season

- platform: environment_canada
  latitude: !secret latitude
  longitude: !secret longitude