###########################################
# Gate Sensors
###########################################

- platform: template
  sensors:
    front_gate:
        value_template: >-
          {%- if is_state("binary_sensor.front_gate", "on") %}
              Open
          {%- elif is_state("binary_sensor.front_gate", "off") %}
              Closed
          {%- else %}
              Error
          {%- endif %}
        friendly_name: 'Front Gate'
        icon_template: >-
            {%- if is_state('binary_sensor.front_gate', 'off') %}
            mdi:gate
            {%- elif is_state('binary_sensor.front_gate', 'on') %}
            mdi:gate-open
            {% else %}
            mdi:gate
            {% endif %}   

- platform: template
  sensors:
    back_gate:
        value_template: >-
          {%- if is_state("binary_sensor.back_gate", "on") %}
              Open
          {%- elif is_state("binary_sensor.back_gate", "off") %}
              Closed
          {%- else %}
              Error
          {%- endif %}
        friendly_name: 'Back Gate'
        icon_template: >-
            {%- if is_state('binary_sensor.back_gate', 'off') %}
            mdi:gate
            {%- elif is_state('binary_sensor.back_gate', 'on') %}
            mdi:gate-open
            {% else %}
            mdi:gate
            {% endif %}   